# Generated by Django 4.0.4 on 2022-07-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_for', models.CharField(max_length=25)),
                ('confidence', models.IntegerField()),
                ('content', models.IntegerField()),
                ('fluency', models.IntegerField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_calc.author')),
            ],
        ),
    ]
