# Generated by Django 4.0.4 on 2022-07-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='content',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='fluency',
            field=models.FloatField(),
        ),
    ]
