# Generated by Django 4.0.4 on 2022-05-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='namer',
        ),
    ]
