# Generated by Django 4.0.4 on 2022-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_name_category_namer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=b'I01\n', upload_to=''),
        ),
    ]
