# Generated by Django 4.0.4 on 2022-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
