# Generated by Django 4.0.4 on 2022-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_maincategory_category_main_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='main_category_image',
            field=models.ImageField(blank=True, upload_to='photos/maincategory'),
        ),
    ]
