# Generated by Django 4.0.4 on 2022-06-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_cate',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
