# Generated by Django 4.0.4 on 2022-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_maincategory_category_main_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_product4',
            field=models.ImageField(blank=True, upload_to='photos/products2'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_product5',
            field=models.ImageField(blank=True, upload_to='photos/products3'),
        ),
    ]
