# Generated by Django 4.0.4 on 2022-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_products_image_product4_products_image_product5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=True, max_length=300, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_product4',
            field=models.ImageField(blank=True, max_length=300, upload_to='photos/products2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_product5',
            field=models.ImageField(blank=True, max_length=300, upload_to='photos/products3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
