# Generated by Django 4.0.4 on 2022-06-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_products_image_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_cate', to='product.maincategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='product.category'),
        ),
    ]
