# Generated by Django 4.0.4 on 2022-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_main_cate_alter_products_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
