# Generated by Django 4.0.4 on 2022-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='namer',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
