# Generated by Django 4.0.4 on 2022-06-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
