# Generated by Django 4.0.4 on 2022-06-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0004_cartproduct_delivery_date_cartproduct_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
