# Generated by Django 4.0.4 on 2022-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0005_remove_cartproduct_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DELIVERED', 'DELIVERED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=20),
        ),
    ]
