# Generated by Django 4.0.4 on 2022-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0007_order_order_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DELIVERED', 'DELIVERED'), ('CANCELED', 'CANCELED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
