# Generated by Django 4.0.4 on 2022-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0011_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('PAYPAL', 'PAYPAL'), ('RAZORPAY', 'RAZORPAY'), ('COD', 'COD')], max_length=20, null=True),
        ),
    ]
