# Generated by Django 4.0.4 on 2022-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0012_order_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_offer',
            field=models.IntegerField(default=0),
        ),
    ]
