# Generated by Django 4.0.4 on 2022-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DELIVERED', 'DELIVERED'), ('CANCELED', 'CANCELED'), ('FAILED', 'FAILED'), ('SHIPPED', 'SHIPPED'), ('OUT FOR DEIVERY', 'OUT FOR DELIVERY')], default='ACCEPTED', max_length=20),
        ),
    ]
