# Generated by Django 4.0.4 on 2022-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
