# Generated by Django 4.0.4 on 2022-06-18 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_accounts_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='referal_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
