# Generated by Django 4.0.4 on 2022-06-19 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_accounts_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='referal_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
